name: Build and release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 代码检出
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 安装 .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: 恢复依赖
        run: dotnet restore .\db_manager\db_manager.csproj

      - name: 构建应用
        run: |
          $version = "${{ github.ref_name }}" -replace '^v', ''
          dotnet publish .\db_manager\db_manager.csproj `
            -c Release `
            -r win-x64 `
            --self-contained true `
            -p:PublishSingleFile=true `
            -p:PublishReadyToRun=true `
            -p:Version=$version `
            --output ./bin/win-x64

      - name: 安装 Inno Setup
        run: |
          choco install innosetup -y --no-progress --force
        shell: powershell

      - name: 构建安装包
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "$env:GITHUB_WORKSPACE\installer.iss"

      - name: 安装 git-chglog
        run: |
          choco install git-chglog -y --no-progress
        shell: powershell

      - name: 生成变更日志
        id: changelog
        run: |
          # 初始化 git-chglog 配置（如果不存在）
          if (-not (Test-Path .chglog/config.yml)) {
            git-chglog --init
          }
          
          # 生成变更日志
          git-chglog -o CHANGELOG.md ${{ github.ref_name }}

          # 读取内容并编码为 base64
          $commits = Get-Content -Path CHANGELOG.md -Raw
          $changelog_base64 = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($commits))
          "CHANGELOG_BASE64=$changelog_base64" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
        shell: powershell

      - name: 准备发布文件
        run: |
          mkdir artifacts
          Copy-Item .\dist\DBManagerSetup.exe .\artifacts\DBManager-${{ github.ref_name }}-Setup.exe
          Compress-Archive -Path .\bin\win-x64\* -DestinationPath .\artifacts\DBManager-${{ github.ref_name }}-Portable.zip
          (Get-FileHash .\artifacts\DBManager-${{ github.ref_name }}-Setup.exe -Algorithm SHA256).Hash | Out-File -Encoding ASCII .\artifacts\DBManager-${{ github.ref_name }}-Setup.exe.sha256
          (Get-FileHash .\artifacts\DBManager-${{ github.ref_name }}-Portable.zip -Algorithm SHA256).Hash | Out-File -Encoding ASCII .\artifacts\DBManager-${{ github.ref_name }}-Portable.zip.sha256
          Copy-Item .\CHANGELOG.md .\artifacts\CHANGELOG-${{ github.ref_name }}.md

      - name: 发布到 GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body_path: CHANGELOG.md
          files: |
            artifacts/DBManager-${{ github.ref_name }}-Setup.exe
            artifacts/DBManager-${{ github.ref_name }}-Setup.exe.sha256
            artifacts/DBManager-${{ github.ref_name }}-Portable.zip
            artifacts/DBManager-${{ github.ref_name }}-Portable.zip.sha256
            artifacts/CHANGELOG-${{ github.ref_name }}.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
