name: Build and release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 代码检出
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 安装 .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: 恢复依赖
        run: dotnet restore .\db_manager\db_manager.csproj

      - name: 构建应用
        run: |
          $version = "${{ github.ref_name }}" -replace '^v', ''
          dotnet publish .\db_manager\db_manager.csproj `
            -c Release `
            -r win-x64 `
            --self-contained true `
            -p:PublishSingleFile=true `
            -p:PublishReadyToRun=true `
            -p:Version=$version `
            --output ./bin/win-x64

      - name: 安装 Inno Setup
        run: |
          choco install innosetup -y --no-progress --force
        shell: powershell

      - name: 构建安装包
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "$env:GITHUB_WORKSPACE\installer.iss"

      - name: Generate changelog
        id: gen_changelog
        uses: bdashrad/git-chglog-action@v2.0.3
        with:
          next_version: "${{ github.ref_name }}".replace('v', '')  # 移除 'v' 前缀
        env:
          CHGLOG_CONFIG: .chglog/config.yml

      - name: 准备发布文件
        run: |
          mkdir artifacts
          Copy-Item .\dist\DBManagerSetup.exe .\artifacts\DBManager-${{ github.ref_name }}-Setup.exe
          Compress-Archive -Path .\bin\win-x64\* -DestinationPath .\artifacts\DBManager-${{ github.ref_name }}-Portable.zip
          (Get-FileHash .\artifacts\DBManager-${{ github.ref_name }}-Setup.exe -Algorithm SHA256).Hash | Out-File -Encoding ASCII .\artifacts\DBManager-${{ github.ref_name }}-Setup.exe.sha256
          (Get-FileHash .\artifacts\DBManager-${{ github.ref_name }}-Portable.zip -Algorithm SHA256).Hash | Out-File -Encoding ASCII .\artifacts\DBManager-${{ github.ref_name }}-Portable.zip.sha256
          Copy-Item .\CHANGELOG.md .\artifacts\CHANGELOG-${{ github.ref_name }}.md

      - name: 发布到 GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body_path: CHANGELOG.md
          files: |
            artifacts/DBManager-${{ github.ref_name }}-Setup.exe
            artifacts/DBManager-${{ github.ref_name }}-Setup.exe.sha256
            artifacts/DBManager-${{ github.ref_name }}-Portable.zip
            artifacts/DBManager-${{ github.ref_name }}-Portable.zip.sha256
            artifacts/CHANGELOG-${{ github.ref_name }}.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
